INSERT INTO products (name, price, seller_id, description, image_url_one, available, sold) VALUES ('Yamaha XT500 Bike', 1900, 01, 'Lightweight, sophisticated and extremely effective – what more could you want in a tourer? The secret to BMW success with the R1200RT is the partially water-cooling engine design which adds an extra bite to the bike',
 'https://wallpaper.dog/large/20493171.jpg',
  true, false);

INSERT INTO products (name, price, seller_id, description, image_url_one, available, sold) VALUES ('Multistrada', 2300, 02, 'The Multistrada range has been in creation since 2003 and as it’s essentially a hybrid of a supermoto and a sport-tourer motorcycle. The Multistrada 1000DS was the first bikes to be created of its type that featured a 992cc air-cooled V-twin engine, however updates have been made to the model to make it one of the best touring bikes for British roads.',
 'https://wallpaper.dog/large/20493224.jpg', true, false);

INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Suzuki V Strom 650', 2370, 2, 'Classed as a middleweight sport touring motorcycle by Suzuki, the V Strom 650 is fit for any purpose due to its adaptability of riding conditions including; commuting, cruising, adventure, touring, and even a degree of off-road riding too! Since the release of the production in 2004, the V Strom is now in its second generation of motorcycles (released in 2012)', 'https://wallpaper.dog/large/20493242.jpg', true, false);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Ducati 916', 2330, 1, 'Debuting in 1994, the 916 was remarked for its new design and updated technical features which saw a brand new water-cooled engine with a larger displacement and a new management system, this put any predecessors firmly in the place Ducati were playing with the big boys now!

Ducati may have created a smaller motorbike but it was still packed with power, an impressive chrome-moly trellis frame and stunning new bodywork with aggressive lines. Ducati’s 916 have been stated as ‘one of the most influential machines of the last twenty years’ by journalist Kevin Ash.', 'https://wallpaper.dog/large/20493308.jpg', true, false);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Harley Davidson Road King', 2570, 2, 'Tourers are iconic for their large saddle bags, rear coil-over suspension and full fairings. Over the years the Road King has had many updates and modifications including new anti-lock braking systems, cruise control and even new frames and swing arm!', 'https://wallpaper.dog/large/20493315.jpg', false, true);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('KTM RC8 ', 2392, 2, 'Honda’s Super Blackbird is one of the most comfortable, useable sports tourers available on the market- no surprise it made our shortlist! Production began in 1996 to challenge Kawasaki’s Ninja ZX-11 as the fastest production motorcycle and Honda successful achieved with a top speed of 178.5mph.', 'https://c4.wallpaperflare.com/wallpaper/58/488/942/bike-audi-audi-carbon-wallpaper-thumb.jpg', true, false);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Honda Blackbird', 2880, 1, 'Suzuki’s GSXR750 has been in constant production since 1985, also known as ‘Gixxer’, the sports bike looks like a Suzuki Endurance motorcycle, but it’s one of the most affordable, modern race replicas you can get your hands on. Dependent on generation, Gixxers are a mixture of slabbies (air-cooled, with flat bodies) and slingshots (oil-cooled due to the introduction of carburetors) models.

“As a 68 year old, my favourite two that I have owned are 650 Bonneville and GSXR 750 completely different but both great bikes!” Pete Haywood', 'https://m.media-amazon.com/images/I/81PjU3ucECL._AC_SL1500_.jpg', true, false);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Kawasaki Ninja H2R', 1750, 1, 'One of the newest models released by Kawasaki in early 2015, and still very desirable amongst many bikers. The supercharged supersport motorcycle claims 300 horsepower and can exceed over 200 miles per hour. The street-legal version still has an impressive out-put of 200hp, ABS, traction control, launch control and bodywork made of carbon fibre to make it as aerodynamic as possible.', 'https://c4.wallpaperflare.com/wallpaper/568/868/905/bike-background-sport-bike-wallpaper-preview.jpg', true, true);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Suzuki 600 Bandit', 1180, 1, 'The success of Suzuki’s 600 Bandit saw the creation of a whole new class of motorcycles – the budget middleweight roadsters. The supersport engine fixed with a basic roadster chassis and you get yourself a best-selling Bandit machine. Named as one of the perfect machines for all types of riders due to versatility on the road.

“Suzuki Bandit for years, but now the Tiger 1050, all round brilliance.” Graham Dodsworth', 'https://c4.wallpaperflare.com/wallpaper/810/426/499/autumn-bike-sport-bike-bicycle-hd-wallpaper-preview.jpg', true, false);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('CBR900R Urban Tiger Fireblade', 2420, 2, 'Honda’s limited edition ‘Urban Tiger’ is known for its paint scheme – it’s one you won’t forget. The 1994 model is still in hot demand by collectors for its impeccable paint scheme, truly living up to its feline name. The spec is impressive too with a liquid-cooled, 16v 893cc inline four engine producing 124bhp. 20 years later and it’s still one of the highest ranked, most desirable bikes out there, well done Honda!', 'hhttps://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/ride-girls-bikes-1638798553.jpg?resize=980:*', false, false);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Kawasaki Versys', 4800, 1, 'The Versys range by Kawasaki is truly one of a kind with each model purpose built for all reasons – commuting to touring or just for the ride – the machines are truly versatile! Versys 650 is a popular model with some impressive specs including liquid-cooled engine, 4 stroke parallel-twin and plenty of power behind it.', 'https://c4.wallpaperflare.com/wallpaper/266/736/56/bike-background-sport-bike-wallpaper-preview.jpg', true, true);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Yamaha PW50', 2250, 1, 'iRated as one of the most influential motorcycles of the modern day because of it’s accessibility for children. If you want to get your kid on two-wheels then the Yamaha PW50 is the perfect starting pointing with three gears, auto clutch and autolube. Once they’ve outgrown the PW50, you can try out the PW80.', 'https://wallpaper.dog/large/20493343.jpg', true, false);
