INSERT INTO products (name, price, seller_id, description, image_url_one, available, sold) VALUES ('Mountain Bike', 100, 01, 'A blue mountain bike',
 'https://media.karousell.com/media/photos/products/2018/11/23/specialized_blue_mountain_bike_1542952739_f7fc155b_progressive.jpg',
  true, false);

INSERT INTO products (name, price, seller_id, description, image_url_one, available, sold) VALUES ('Coffee Cup', 200, 02, 'A brown cup for sale',
 'https://m.media-amazon.com/images/I/81PjU3ucECL._AC_SL1500_.jpg', true, false);

INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Fond - Neutral', 237, 2, 'hac habitasse platea dictumst etiam faucibus cursus urna', 'https://cdn.shopify.com/s/files/1/0588/3900/7387/products/velo_gris_45_v2_1800x1800.jpg?v=1629143605', false, false);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Wine - Jaboulet Cotes Du Rhone', 233, 1, 'in tempor turpis nec euismod scelerisque quam', 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/ride-girls-bikes-1638798553.jpg?resize=980:*', true, false);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Wine - Guy Sage Touraine', 257, 2, 'sem mauris laoreet ut rhoncus aliquet pulvinar', 'https://images.unsplash.com/photo-1611429532458-f8bf8f6121fe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=679&q=80', false, true);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Lettuce - Lolla Rosa', 232, 2, 'aliquet pulvinar sed nisl nunc', 'https://m.media-amazon.com/images/I/81PjU3ucECL._AC_SL1500_.jpg', true, false);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Sprouts - Alfalfa', 288, 1, 'nec nisi volutpat eleifend donec ut', 'https://m.media-amazon.com/images/I/81PjU3ucECL._AC_SL1500_.jpg', true, false);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Potatoes - Pei 10 Oz', 175, 1, 'id mauris vulputate elementum nullam varius nulla', 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/ride-girls-bikes-1638798553.jpg?resize=980:*', true, true);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('V8 - Tropical Blend', 118, 1, 'ornare imperdiet sapien urna pretium nisl ut volutpat', 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/ride-girls-bikes-1638798553.jpg?resize=980:*', true, false);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Soap - Hand Soap', 242, 2, 'quis odio consequat varius integer ac leo pellentesque ultrices mattis', 'hhttps://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/ride-girls-bikes-1638798553.jpg?resize=980:*', false, false);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('French Pastry - Mini Chocolate', 8, 1, 'condimentum curabitur in libero ut massa', 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/ride-girls-bikes-1638798553.jpg?resize=980:*', true, true);
INSERT INTO products (name, price, seller_id, description,   image_url_one, available, sold) VALUES ('Extract - Almond', 225, 1, 'ipsum dolor sit amet consectetuer adipiscing elit proin', 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/ride-girls-bikes-1638798553.jpg?resize=980:*', true, false);
